# Generated by Django 4.2.2 on 2023-06-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='xyz.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='available_stock',
            field=models.IntegerField(default=0),
        ),
    ]
