# Generated by Django 4.2.2 on 2023-06-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_productcategorymapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='contact',
            field=models.IntegerField(default=1234567890, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='bihar', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='town',
            field=models.CharField(default='town', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delievery_charge',
            field=models.IntegerField(default=100),
        ),
    ]
