# Generated by Django 4.2.2 on 2023-06-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_wishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='verified_status',
            field=models.BooleanField(default=True),
        ),
    ]
