# Generated by Django 4.2.2 on 2023-06-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_review_verified_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.AddField(
            model_name='item',
            name='reviews',
            field=models.ManyToManyField(to='mainapp.review'),
        ),
    ]
