# Generated by Django 4.2.2 on 2023-06-27 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_item_reviews_item_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='reviews',
        ),
        migrations.CreateModel(
            name='ItemReviewMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.item')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.review')),
            ],
        ),
    ]
