# Generated by Django 4.2.2 on 2023-07-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_remove_item_reviews_itemreviewmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_back',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='item',
            name='image_cross',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='item',
            name='image_side',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
    ]
