# Generated by Django 4.2.2 on 2023-07-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_item_image_back_item_image_cross_item_image_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_back',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_cross',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_side',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
