# Generated by Django 4.2.2 on 2023-07-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_alter_item_image_back_alter_item_image_cross_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='small', max_length=100),
        ),
    ]
